#ifndef ICHARGER_MESSAGE_KEYS_H
#define ICHARGER_MESSAGE_KEYS_H

#include <QString>

const QString STR_DEVICE_ONLY_ID;
const QString STR_DEVICE_ONLY_SERIAL_NUMBER;
const QString STR_DEVICE_ONLY_SW_VERSION;
const QString STR_DEVICE_ONLY_HW_VERSION;
const QString STR_DEVICE_ONLY_CH1_STATUS;
const QString STR_DEVICE_ONLY_CH2_STATUS;

#endif // ICHARGER_MESSAGE_KEYS_H
