#ifndef ICHARGER_MESSAGE_KEYS_H
#define ICHARGER_MESSAGE_KEYS_H

#include <QString>

// DeviceOnly
extern const QString STR_DEVICE_ONLY_ID;
extern const QString STR_DEVICE_ONLY_SERIAL_NUMBER;
extern const QString STR_DEVICE_ONLY_SW_VERSION;
extern const QString STR_DEVICE_ONLY_HW_VERSION;
extern const QString STR_DEVICE_ONLY_CH1_STATUS;
extern const QString STR_DEVICE_ONLY_CH2_STATUS;
extern const QString STR_DEVICE_ONLY_MANUFACTURER;
extern const QString STR_DEVICE_ONLY_PRODUCT;

// ChannelStatus
extern const QString STR_CHANNEL_STATUS_CHANNEL_NUM;
extern const QString STR_CHANNEL_STATUS_OUTPUT_POWER;
extern const QString STR_CHANNEL_STATUS_OUTPUT_CURRENT;
extern const QString STR_CHANNEL_STATUS_OUTPUT_VOLTAGE;
extern const QString STR_CHANNEL_STATUS_OUTPUT_CAPACITY;

extern const QString STR_CHANNEL_STATUS_INPUT_VOLTAGE;

extern const QString STR_CHANNEL_STATUS_TEMP_INTERNAL;
extern const QString STR_CHANNEL_STATUS_TEMP_EXTERNAL;

extern const QString STR_CHANNEL_STATUS_CELLS;
extern const QString STR_CHANNEL_STATUS_CELL_NUMBER;
extern const QString STR_CHANNEL_STATUS_CELL_VOLTAGE;
extern const QString STR_CHANNEL_STATUS_CELL_BALANCE_STATUS;
extern const QString STR_CHANNEL_STATUS_CELL_RESISTANCE;

extern const QString STR_CHANNEL_STATUS_TOTAL_RESISTANCE;
extern const QString STR_CHANNEL_STATUS_LINE_INTERNAL_RESISTANCE;
extern const QString STR_CHANNEL_STATUS_CYCLE_COUNT;
extern const QString STR_CHANNEL_STATUS_CONTROL_STATUS;
extern const QString STR_CHANNEL_STATUS_RUN_STATUS;
extern const QString STR_CHANNEL_STATUS_RUN_ERROR;
extern const QString STR_CHANNEL_STATUS_DIALOG_BOX_ID;

#endif // ICHARGER_MESSAGE_KEYS_H
